# Generated by Django 4.1.3 on 2023-05-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.CharField(max_length=200, verbose_name="Адрес магазина"),
        ),
    ]
